apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ./../../manifests

images:
- name: PROJECT/IMAGE1
  newName: mo3mo3/todo-front
  newTag: ea6cbbcf04160e9138cd9edd328b9fdd3f3155bd
- name: PROJECT/IMAGE2
  newName: mo3mo3/backend
  newTag: ea6cbbcf04160e9138cd9edd328b9fdd3f3155bd
- name: PROJECT/IMAGE3
  newName: mo3mo3/broadcaster
  newTag: ea6cbbcf04160e9138cd9edd328b9fdd3f3155bd
