apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production

resources:
- ./../../manifests
- cronjob.yaml
- persistentVolumeClaim.yaml

images:
- name: PROJECT/IMAGE1
  newName: mo3mo3/todo-front
  newTag: v3
- name: PROJECT/IMAGE2
  newName: mo3mo3/backend
  newTag: v6
- name: PROJECT/IMAGE3
  newName: mo3mo3/broadcaster
  newTag: v1
