apiVersion: v1
kind: ConfigMap
metadata:
  name: back-config
data:
  DB_HOST: db-svc
  DB_NAME: postgres
  DB_USERNAME: moataz
  DB_PASSWORD: "1234"
  NATS_URL: nats://my-nats:4222
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: moataz
